config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'dashboards#index'

  devise_for :users, skip: %i[registrations omniauth_callbacks unlocks], controllers: {
    confirmations: 'devise/users/confirmations',
    # omniauth_callbacks: 'devise/users/omniauth_callbacks',
    passwords: 'devise/users/passwords',
    # registrations: 'devise/users/registrations',
    sessions: 'devise/users/sessions'
  }

  devise_scope :user do
    get '/users/:referral_username/sign_up', to: 'devise/users/registrations#new', as: 'new_indication'
    get '/users/edit', to: 'devise/users/registrations#edit', as: 'edit_user_registration'
    patch '/users', to: 'devise/users/registrations#update', as: 'user_registration'
    put '/users', to: 'devise/users/registrations#update'
    post '/users', to: 'devise/users/registrations#create'
    get '/users/cancel', to: 'devise/users/registrations#cancel', as: 'cancel_user_registration'
    delete '/users', to: 'devise/users/registrations#destroy'
  end

  devise_for :admins, skip: %i[confirmations passwords registrations], controllers: {
    # confirmations: 'devise/admins/confirmations',
    # passwords: 'devise/admins/passwords',
    # registrations: 'devise/admins/registrations',
    sessions: 'devise/admins/sessions'
  }, path: '', path_names: { sign_in: 'nAw9D7t2hCLBJwDjPHnUhZJnSyESpf24cxjfsX6tvzCXHMVEahHf3qwyEg2r5DLy' }

  resources :addresses, except: %i[index show destroy]
  get 'addresses/:id/edit_by_admin' => 'addresses#edit_by_admin', as: 'edit_address_by_admin'

  get 'clients' => 'users#index_clients', as: 'index_clients'
  get 'clients_by_admin/:id' => 'users#index_clients_by_admin', as: 'clients_by_admin'
  get 'users' => 'users#index', as: 'index_users_by_admin'
  get 'users/:id/edit' => 'users#edit', as: 'edit_user_by_admin'
  patch 'users/:id' => 'users#update', as: 'user'

  resources :deposits, except: %i[edit update destroy] 
  match '548d82xh4gg5xt6cy8chvxnm6nmxvk6g' => 'deposits#create_btc', :via => :post
  get 'deposits_by_admin' => 'deposits#index_by_admin', as: 'deposits_by_admin'
  get 'deposits/:user_id/list' => 'deposits#list', as: 'deposits_list'

  resources :investiments, except: %i[destroy]
  get 'investiments_by_admin' => 'investiments#index_by_admin', as: 'investiments_by_admin'
  get 'investiments/activate/:id' => 'investiments#activate', as: 'activate_investiment'
  get 'investiments/disable/:id' => 'investiments#disable', as: 'disable_investiment'
  get 'investiments/:user_id/list' => 'investiments#list', as: 'investiments_list'
  post 'investiments/:user_id' => 'investiments#create_by_admin', as: 'create_investiment_by_admin'
  patch 'investiments/:id/edit_values' => 'investiments#edit_values', as: 'edit_investiment_values'

  resources :remunerations, except: %i[new create destroy show]
  get 'remunerations/pay/:id' => 'remunerations#pay', as: 'pay_remuneration'

  resources :btc_withdraws, except: %i[show update destroy]
  patch 'btc_withdraws/apply_penalty/:id' => 'btc_withdraws#apply_penalty', as: 'apply_penalty'
  get 'btc_withdraws_by_admin' => 'btc_withdraws#index_by_admin', as: 'btc_withdraws_by_admin'
  get 'btc_withdraws/confirm_withdraw/:id' => 'btc_withdraws#confirm_withdraw', as: 'confirm_withdraw'
  get 'btc_withdraws/reverse_withdraw/:id' => 'btc_withdraws#reverse_withdraw', as: 'reverse_withdraw'
  match 'e6157772b13beb9adda4e690f623e742' => 'btc_withdraws#update_confirmations', :via => :post
  get 'btc_withdraws/:user_id/list' => 'btc_withdraws#list', as: 'btc_withdraws_list'
  get 'btc_withdraws/:destination/:token' => 'btc_withdraws#confirm_withdraw_request', as: 'confirm_withdraw_request'
  get 'btc_withdraw/resend_withdraw_mail/:id' => 'btc_withdraws#resend_withdraw_mail', as: 'resend_withdraw_mail'

  get 'launches/:user_id' => 'launches#index', as: 'launches'
  post 'launches/:user_id' => 'launches#create'

  resources :contacts, only: %i[new create]
  patch 'packages/:id' => 'packages#update_remuneration_rate', as: 'package'

  get 'extracts/:user_id' => 'extracts#show', as: 'show_extracts_by_admin'

  get 'reports/financial_report' => 'reports#financial_report', as: 'financial_report'

  get 'uploads/new' => 'uploads#new', as: 'new_upload'

  # post 'uploads/' => 'uploads#create', as: 'uploads'

  #banks
  resources :banks, except: [:show]

  #bank_account
  resources :bank_account_clients, only: [:index, :create, :destroy]
  devise_scope :bank_account_clients do
    get "bank_account_clients_admin/:user_id" => "bank_account_clients#edit_admin", as: "bank_account_clients_admin"
    post "bank_account_clients_admin/:user_id" => "bank_account_clients#create_admin", as: "bank_account_clients_create_admin"
    get "bank_account_clients/new" => "bank_account_clients#new", as: "new_bank_account_client"
  end


end

app/models/btc_withdraw.rb
# frozen_string_literal: true

class BtcWithdraw < ApplicationRecord
  extend Enumerize

  NETWORK_FEE = 40_000
  MINIMAL_WITHDRAW = 150.0
  AVAILABLE = true

  belongs_to :user
  has_one :btc_wallet, through: :user
  validates :amount, presence: true
  validates :amount, numericality: { greater_than_or_equal_to: NETWORK_FEE }
  validates :final_amount, presence: true
  validates :value, presence: true
  validates :value, numericality: { greater_than_or_equal_to: MINIMAL_WITHDRAW }
  validates :destination, presence: true
  validate :valid_address?, on: :create, if: -> { Rails.env.production? }

  enumerize :status, in: %i[pending_email request_created confirmed unconfirmed canceled reversed], default: :pending_email
  enumerize :penalty_rate, in: { '5%': 5, '10%': 10, '15%': 15, '20%': 20, '25%': 25, '30%': 30,
                                 '35%': 35, '40%': 40, '45%': 45, '50%': 50 }
  validate :available
  after_create :debit

  def set_attributes
    set_cotation
    set_amount
    create_unique_token
   end

  def set_cotation
    result = JSON.parse(RestClient.get('https://blockchain.info/ticker'))
    self.btc_cotation = (result['USD']['last']).round(2)
  end

  def set_amount
    amount = value.round(2) / btc_cotation
    self.amount = amount.to_satoshi
    # self.final_amount = amount.to_satoshi - NETWORK_FEE
    self.final_amount = amount.to_satoshi
  end

  def apply_penalty(penalty_rate)
    penalty_value = value * (penalty_rate.to_f / 100)
    penalty_amount = final_amount * (penalty_rate.to_f / 100)
    updated_final_amount = final_amount - penalty_amount
    update(penalty_value: penalty_value, penalty_rate: penalty_rate, penalty_amount: penalty_amount, final_amount: updated_final_amount)
  end

  def withdraw
    total_amount = final_amount.abs
    ActiveRecord::Base.transaction do
      raise ActiveRecord::Rollback unless
      @transaction = blockcypher.send_money(Rails.application.credentials[Rails.env.to_sym][:wallets][:hot_wallet_address],
                                            destination, total_amount.abs, Rails.application.credentials[Rails.env.to_sym][:wallets][:hot_wallet_private])
    end
    if @transaction
      transaction_params = {
        transaction_hash: @transaction['tx']['hash'],
        status: :unconfirmed,
        confirmations: @transaction['tx']['confirmations'],
        fee: @transaction['tx']['fees'],
        # absorved_rate: get_absorved_rate,
        token: nil
      }
      update(transaction_params)
    end
  rescue BlockCypher::Api::Error => e
    logger.info(e)
    errors.add(:destination, I18n.t('validations.withdrawals.transaction_error'))
    update_attributes(status: :request_created, token: nil)
  end

  def debit
    if user.account.has_enough_available_funds?(value)
      user.account.debit_available(value)
    else
      errors.add(:amount, I18n.t('validations.withdrawals.insufficient_funds'))
      raise ActiveRecord::Rollback
      false
    end
  end

  def reverse
    if (status.pending_email? || status.request_created?) && transaction_hash.nil?
      user.account.credit_available(value)
      update_attribute(:status, :reversed)
    else
      errors.add(:amount, I18n.t('validations.withdrawals.already_maked'))
      false
    end
  end

  def admin_confirm_withdraw
    confirmations = blockcypher.blockchain_transaction(transaction_hash)
    if confirmations['confirmations'] > 0
      update_attribute(:status, :confirmed)
    else
      errors.add(:status, I18n.t('validations.withdrawals.successfully_confirmed'))
      false
    end
  end

  def update_token
    create_unique_token
    update_attribute(:token, token)
  end

  private

  def valid_address?
    unless Bitcoin.valid_address? destination
      errors.add(:destination, I18n.t('validations.withdrawals.invalid_address'))
      false
    end
  end

  # def get_absorved_rate
  #   NETWORK_FEE - @transaction['tx']['fees']
  # end

  def create_unique_token
    loop do
      self.token = SecureRandom.hex(10) # or whatever you chose like UUID tools
      break unless self.class.exists?(token: token)
    end
  end

  def available
    unless AVAILABLE
      errors.add(:destination, 'Saque temporariamente indisponível. Estamos em manutenção. Em breve estará de volta :)')
      false
    end
  end
end

app/controllers/btc_withdraws_controller.rb
# frozen_string_literal: true

class BtcWithdrawsController < ApplicationController
  load_and_authorize_resource except: [:update_confirmations, :confirm_withdraw_request]
  skip_before_action :verify_authenticity_token, only: [:update_confirmations]

  before_action :set_transaction, only: [:update_confirmations]

  before_action :set_btc_withdraw, only: %i[show confirm_withdraw reverse_withdraw resend_withdraw_mail]

  before_action :set_btc_withdraw_by_hash, only: %i[update_confirmations]

  before_action :set_user, only: %i[list]

  # GET /btc_withdraws
  # GET /btc_withdraws.json
  def index
    redirect_to root_path, notice: t("common.awaiting")
    @btc_withdraws = current_user.btc_withdraws
  end

  def index_by_admin
    redirect_to root_path, notice: t("common.awaiting")

    all_btc_withdraws = BtcWithdraw.all
    if params[:status] == 'pending_email'
      @btc_withdraws = all_btc_withdraws.where(status: :pending_email)
    elsif params[:status] == 'request_created'
      @btc_withdraws = all_btc_withdraws.where(status: :request_created)
    elsif params[:status] == 'confirmed'
      @btc_withdraws = all_btc_withdraws.where(status: :confirmed)
    elsif params[:status] == 'unconfirmed'
      @btc_withdraws = all_btc_withdraws.where(status: :unconfirmed)
    elsif params[:status] == 'canceled'
      @btc_withdraws = all_btc_withdraws.where(status: :canceled)
    elsif params[:status] == 'reversed'
      @btc_withdraws = all_btc_withdraws.where(status: :reversed)
    elsif params[:status] == 'all'
      @btc_withdraws = all_btc_withdraws
    end
  end

  # GET /btc_withdraws/1/edit
  def edit; end

  # GET /btc_withdraws/new
  def new
    redirect_to root_path, notice: t("common.awaiting")
    @btc_withdraw = BtcWithdraw.new
  end

  # POST /btc_withdraws
  # POST /btc_withdraws.json
  def create
    respond_to do |format|
      if current_user.can_withdraw?
        @btc_withdraw = BtcWithdraw.new(btc_withdraw_params)
        @btc_withdraw.user = current_user
        @btc_withdraw.set_attributes
        if verify_recaptcha(model: @btc_withdraw) && @btc_withdraw.save
          send_email_to_confirm(current_user, @btc_withdraw)
          format.html { redirect_to btc_withdraws_path, notice: t('withdrawals.successfully_created') }
          format.json { render :edit, status: :created, location: @btc_withdraw }
        else
          format.html { render :new }
          format.json { render json: @btc_withdraw.errors, status: :unprocessable_entity }
        end
      else
        format.html { redirect_to root_path, alert: t("withdrawals.cant_withdraw.#{current_user.level}") }
      end
    end
  end

  # PATCH/PUT /btc_withdraws/1
  # PATCH/PUT /btc_withdraws/1.json
  def apply_penalty
    respond_to do |format|
      if @btc_withdraw.apply_penalty(params[:btc_withdraw][:penalty_rate])
        format.html { redirect_to edit_btc_withdraw_path(@btc_withdraw), notice: 'Value successfully updated.' }
        format.json { render :edit, status: :ok, location: @btc_withdraw }
      else
        format.html { render :edit }
        format.json { render json: @btc_withdraw.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm_withdraw
    respond_to do |format|
      @btc_withdraw.withdraw
      if @btc_withdraw.status.unconfirmed?
        format.html { redirect_to edit_btc_withdraw_path(@btc_withdraw), notice: 'Withdraw sucessfully created!' }
        format.json { render json: @btc_withdraw.errors, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @btc_withdraw.errors, status: :unprocessable_entity }
      end
    end
  end

  def confirm_withdraw_request
    btc_withdraw = BtcWithdraw.find_by(token: params[:token], destination: params[:destination], status: :pending_email)
    respond_to do |format|
      if btc_withdraw && Time.zone.now < (btc_withdraw.updated_at + 3.hours)
        btc_withdraw.update_attribute(:status, :request_created)
        format.html { redirect_to root_path, notice: t("withdrawals.request_successfully_confirmed") }
      else 
        format.html { redirect_to root_path, alert: t("validations.withdrawals.confirm_withdraw_request_error")}
      end
    end
  end

  def resend_withdraw_mail
    @btc_withdraw.update_token
    send_email_to_confirm(current_user, @btc_withdraw) if @btc_withdraw.status.pending_email? && !@btc_withdraw.token.nil?
    respond_to do |format|
      format.html { redirect_to btc_withdraws_path, notice: t("withdrawals.successfuly_sent") }
    end 
  end 

  def update_confirmations
    respond_to do |format|
      format.html { head :ok }
      format.json { head :ok }
    end
    body = request.raw_post
    api_call = JSON(body)

    if @btc_withdraw.update(confirmations: @transaction['confirmations'], status: :confirmed)
      logger.info(@transaction)
    end
  end

  def reverse_withdraw
    respond_to do |format|
      if @btc_withdraw.reverse
        format.html { redirect_to root_path, notice: 'Withdraw successfuly reversed!' }
        format.json { render json: @btc_withdraw.errors, status: :ok }
      else
        format.html { render :edit, alert: I18n.t('validations.coin_withdraw.coin_withdraw_successfully_confirmed') }
        format.json { render json: @btc_withdraw.errors, status: :unprocessable_entity }
      end
    end
  end

  def list
    @btc_withdraws = @user.btc_withdraws
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_btc_withdraw
    @btc_withdraw = BtcWithdraw.find(params[:id])
  end

  def set_transaction
    @transaction = blockcypher.blockchain_transaction(params[:hash])
  end

  def set_btc_withdraw_by_hash
    @btc_withdraw = BtcWithdraw.where(transaction_hash: @transaction['hash']).first
  end

  def send_email_to_confirm(user, btc_withdraw)
    link_to_confirm = set_link_confirmation(btc_withdraw)
    NotifierWithdrawRequestMailer.request_confirmation(user, btc_withdraw, link_to_confirm).deliver_now
  end

  def set_link_confirmation(btc_withdraw)
    confirm_withdraw_request_url(destination: btc_withdraw.destination, token: btc_withdraw.token)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def btc_withdraw_params
    params.require(:btc_withdraw).permit(:value, :destination)
  end
end

app/helpers/btc_withdraws_helper.rb
module BtcWithdrawsHelper
  def decide_tab_activate(type, type_params)
    if type == type_params
      "nav-link active"
    elsif type_params.nil? && type == "all"
      "nav-link active"
    else
      "nav-link"
    end
  end

  def get_size_filter_content_btc_withdraws(type_params)
    if type_params == "all"
      BtcWithdraw.count
    else
      BtcWithdraw.where(status: type_params).size
    end
  end
end

app/views/btc_withdraws/edit.html.erb
<div class="inner-wrapper">
  <section role="main" class="content-body">
    <header class="page-header">
      <h2>Withdraw</h2>
      <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
          <li>
            <%= link_to root_path do %>
              <i class="fas fa-home"></i>
            <% end %>
          </li>
          <li><span>Withdraw</span></li>
        </ol>
        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fas fa-chevron-left"></i></a>
      </div>
    </header>
    <!-- start: page -->
    <%= render 'notifications'%>
    <% if @btc_withdraw.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@btc_withdraw.errors.count, "error") %> <%=t("validations.form_error_message")%></h2>
        <% @btc_withdraw.errors.full_messages.each do |message| %>
          <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <strong>Error! </strong><%= message %></div>
        <% end %>
      </div>
    <% end %>
    <section class="card">
      <header class="card-header">
        <h2 class="card-title"><%="Withdraw Details"%></h2>
      </header>
      <div class="card-body">
        <div class="col-lg-6">
          <p>
            <strong>Value:</strong>
            <i class="fas fa-dollar-sign"></i> <%= @btc_withdraw.value %>
          </p>
          <p>
            <strong>Penalty Rate:</strong>
            <%= @btc_withdraw.penalty_rate %>
          </p>
          <p>
            <strong>Penalty Value:</strong>
            <i class="fas fa-dollar-sign"></i> <%= @btc_withdraw.penalty_value %>
          </p>
          <p>
            <strong>Btc Cotation:</strong>
            <i class="fas fa-dollar-sign"></i> <%= @btc_withdraw.btc_cotation %>
          </p>
          <p>
            <strong>Transaction hash:</strong>
            <%= @btc_withdraw.transaction_hash %>
          </p>
          <p>
            <strong>Status:</strong>
            <%= @btc_withdraw.status %>
          </p>
          <p>
            <strong>Amount:</strong>
            <i class="fab fa-btc"></i> <%= @btc_withdraw.amount&.to_bitcoin %>
          </p>
          <!--<p>
            <strong>Fee:</strong>
            <i class="fab fa-btc"></i> <%= @btc_withdraw.fee&.to_bitcoin %>
          </p> -->
          <p>
            <strong>Penalty Amount:</strong>
            <i class="fab fa-btc"></i> <%= @btc_withdraw.penalty_amount&.to_bitcoin %>
          </p>
          <p>
            <strong>Final Amount:</strong>
            <i class="fab fa-btc"></i> <%= @btc_withdraw.final_amount&.to_bitcoin %>
          </p>
          <p>
            <strong>Confirmations:</strong>
            <%= @btc_withdraw.confirmations %>
          </p>
          <p>
            <strong>Destination:</strong>
            <%= @btc_withdraw.destination %>
          </p>
          <p>
            <strong>Creation Date:</strong>
            <%= @btc_withdraw.created_at.strftime("%F %T") %>
          </p>
          <!--  <p>
            <strong>Absorved rate:</strong>
            <i class="fab fa-btc"></i> <%= @btc_withdraw.absorved_rate&.to_bitcoin  %>
          </p> -->
          <% if @btc_withdraw.status.pending_email? ||  @btc_withdraw.status.request_created?%>
            <%= form_for @btc_withdraw, url: {action: "apply_penalty"} do |f| %>
              <% if @btc_withdraw.penalty_rate.nil?%>
                <p>
                  <strong>Penalty Rate:</strong>
                </p>
                <div class="input-group mb-3">
                  <%= f.select :penalty_rate, options_for_select(BtcWithdraw.penalty_rate.options, @btc_withdraw.penalty_rate), {}, class: "form-control"%>
                  <span class="input-group-append">
                    <%= f.submit "Apply Penalty", class: "btn btn-warning" %>
                  </span>
                </div>
              <% end %>
            <% end %>
            <%= link_to 'Confirm', confirm_withdraw_path(@btc_withdraw), class: "btn btn-success btn-lg", data: { disable_with: "Processing", confirm: "Are you sure?" } %>
            <%= link_to 'Reverse', reverse_withdraw_path(@btc_withdraw), class: "btn btn-danger btn-lg", data: { disable_with: "Processing", confirm: "Are you sure?" } %>
          <%end%>
        </div>
      </div>
    </section>
    <!-- end: page -->
  </section>
</div>

app/views/btc_withdraws/list.html.erb
<div class="inner-wrapper">
  <section role="main" class="content-body">
    <header class="page-header">
      <h2>Btc Withdrawals</h2>
      <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
          <li>
            <%= link_to root_path do %>
              <i class="fas fa-home"></i>
            <% end %>
          </li>
          <li><span>Btc Withdrawals</span></li>
        </ol>
        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fas fa-chevron-left"></i></a>
      </div>
    </header>
    <!-- start: page -->
    <%= render 'notifications' %>
    <div class="row">
      <div class="col-lg-4 col-xl-3 mb-4 mb-xl-0">
        <section class="card">
          <div class="card-body">
            <div class="thumb-info mb-3">
              <%=image_tag @user.avatar_url(:thumb), class: "rounded img-fluid"%>
              <div class="thumb-info-title">
                <span class="thumb-info-inner"><%=@user.name%></span>
                <span class="thumb-info-type"><%=@user.status%></span>
              </div>
            </div>
            <!-- 
            <div class="widget-toggle-expand mb-3">
              <div class="widget-header">
                <h5 class="mb-2">Profile Completion</h5>
                <div class="widget-toggle">+</div>
              </div>
              <div class="widget-content-collapsed">
                <div class="progress progress-xs light">
                  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
                    60%
                  </div>
                </div>
              </div>
              <div class="widget-content-expanded">
                <ul class="simple-todo-list mt-3">
                  <li class="completed">Update Profile Picture</li>
                  <li class="completed">Change Personal Information</li>
                  <li>Update Social Media</li>
                  <li>Follow Someone</li>
                </ul>
              </div>
            </div>
            <hr class="dotted short">
            <h5 class="mb-2 mt-3">About</h5>
            <p class="text-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam quis vulputate quam. Interdum et malesuada</p>
            <div class="clearfix">
              <a class="text-uppercase text-muted float-right" href="#">(View All)</a>
            </div>
            <hr class="dotted short">
            <div class="social-icons-list">
              <a rel="tooltip" data-placement="bottom" target="_blank" href="http://www.facebook.com" data-original-title="Facebook"><i class="fab fa-facebook-f"></i><span>Facebook</span></a>
              <a rel="tooltip" data-placement="bottom" href="http://www.twitter.com" data-original-title="Twitter"><i class="fab fa-twitter"></i><span>Twitter</span></a>
              <a rel="tooltip" data-placement="bottom" href="http://www.linkedin.com" data-original-title="Linkedin"><i class="fab fa-linkedin-in"></i><span>Linkedin</span></a>
            </div> -->
          </div>
        </section>
      </div>
      <div class="col-lg-8 col-xl-6">
        <div class="tabs">
          <ul class="nav nav-tabs tabs-primary">
            <li class="nav-item">
              <%=link_to "Personal Informations", edit_user_by_admin_path(@user), class: "nav-link"%>
            </li>
            <%if @user.address.present? %>
              <li class="nav-item">
                <%= link_to "Address", edit_address_by_admin_path(@user.address), class: "nav-link" %>
              </li>
            <%end%>
            <li class="nav-item">
              <%= link_to "Clients", clients_by_admin_path(@user), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Deposits", deposits_list_path(@user), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Investiments", investiments_list_path(@user), class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <a class="nav-link active" href="" data-toggle="tab">Withdrawals</a>
            </li>
            <li class="nav-item">
              <%=link_to "Launches", launches_path(@user), class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%=link_to "Extract", show_extracts_by_admin_path(@user), class: "nav-link"%>
            </li>
          </ul>
          <div class="tab-content">
            <div class="tab-pane active">
              <section class="card">
                <header class="card-header">
                  <h2 class="card-title">All Withdrawals</h2>
                </header>
                <div class="card-body">
                  <table class="table table-bordered table-striped mb-0">
                    <thead>
                      <tr>
                        <th>Value</th>
                        <th>BTC Cotation</th>
                        <th>Transaction hash</th>
                        <th>Status</th>
                        <th>Amount</th>
                        <!-- <th>Fee</th> -->
                        <!-- <th>Absorved Rate</th> -->
                        <th>Creation Date</th>
                        <th>Details</th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @btc_withdraws.each do |withdraw| %>
                        <tr>
                          <td><i class="fas fa-dollar-sign"></i> <%= withdraw.value %></td>
                          <td><i class="fas fa-dollar-sign"></i> <%= withdraw.btc_cotation %></td>
                          <td>
                            <%if withdraw.status.confirmed? || withdraw.status.unconfirmed?%>
                              <%= link_to "https://live.blockcypher.com/btc/tx/" + withdraw.transaction_hash,  target: :_blank do %>
                                <i class="fas fa-external-link-alt"></i>
                              <%end%>
                            <%end%>
                          </td>
                          <td><%= withdraw.status %></td>
                          <td><i class="fab fa-btc"></i> <%= withdraw.amount&.to_bitcoin %></td>
                          <!--<td><i class="fab fa-btc"></i> <%= withdraw.fee&.to_bitcoin %></td> -->
                          <!--<td><i class="fab fa-btc"></i> <%= withdraw.absorved_rate&.to_bitcoin %></td>-->
                          <td><%= withdraw.created_at.strftime("%F %T") %></td>
                          <td>
                            <%= link_to edit_btc_withdraw_path(withdraw), target: :_blank  do %>
                              <i class="fas fa-eye"></i>
                            <%end%>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </section>
            </div>
          </div>
        </div>
      </div>
      <%=render "shared/financial_info", user: @user%>
    </div>
    <!-- end: page -->
  </section>
</div>

app/views/btc_withdraws/new.html.erb
<%= render 'form', btc_withdraw: @btc_withdraw %>