config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'dashboards#index'

  devise_for :users, skip: %i[registrations omniauth_callbacks unlocks], controllers: {
    confirmations: 'devise/users/confirmations',
    # omniauth_callbacks: 'devise/users/omniauth_callbacks',
    passwords: 'devise/users/passwords',
    # registrations: 'devise/users/registrations',
    sessions: 'devise/users/sessions'
  }

  devise_scope :user do
    get '/users/:referral_username/sign_up', to: 'devise/users/registrations#new', as: 'new_indication'
    get '/users/edit', to: 'devise/users/registrations#edit', as: 'edit_user_registration'
    patch '/users', to: 'devise/users/registrations#update', as: 'user_registration'
    put '/users', to: 'devise/users/registrations#update'
    post '/users', to: 'devise/users/registrations#create'
    get '/users/cancel', to: 'devise/users/registrations#cancel', as: 'cancel_user_registration'
    delete '/users', to: 'devise/users/registrations#destroy'
  end

  devise_for :admins, skip: %i[confirmations passwords registrations], controllers: {
    # confirmations: 'devise/admins/confirmations',
    # passwords: 'devise/admins/passwords',
    # registrations: 'devise/admins/registrations',
    sessions: 'devise/admins/sessions'
  }, path: '', path_names: { sign_in: 'nAw9D7t2hCLBJwDjPHnUhZJnSyESpf24cxjfsX6tvzCXHMVEahHf3qwyEg2r5DLy' }

  resources :addresses, except: %i[index show destroy]
  get 'addresses/:id/edit_by_admin' => 'addresses#edit_by_admin', as: 'edit_address_by_admin'

  get 'clients' => 'users#index_clients', as: 'index_clients'
  get 'clients_by_admin/:id' => 'users#index_clients_by_admin', as: 'clients_by_admin'
  get 'users' => 'users#index', as: 'index_users_by_admin'
  get 'users/:id/edit' => 'users#edit', as: 'edit_user_by_admin'
  patch 'users/:id' => 'users#update', as: 'user'

  resources :deposits, except: %i[edit update destroy] 
  match '548d82xh4gg5xt6cy8chvxnm6nmxvk6g' => 'deposits#create_btc', :via => :post
  get 'deposits_by_admin' => 'deposits#index_by_admin', as: 'deposits_by_admin'
  get 'deposits/:user_id/list' => 'deposits#list', as: 'deposits_list'

  resources :investiments, except: %i[destroy]
  get 'investiments_by_admin' => 'investiments#index_by_admin', as: 'investiments_by_admin'
  get 'investiments/activate/:id' => 'investiments#activate', as: 'activate_investiment'
  get 'investiments/disable/:id' => 'investiments#disable', as: 'disable_investiment'
  get 'investiments/:user_id/list' => 'investiments#list', as: 'investiments_list'
  post 'investiments/:user_id' => 'investiments#create_by_admin', as: 'create_investiment_by_admin'
  patch 'investiments/:id/edit_values' => 'investiments#edit_values', as: 'edit_investiment_values'

  resources :remunerations, except: %i[new create destroy show]
  get 'remunerations/pay/:id' => 'remunerations#pay', as: 'pay_remuneration'

  resources :btc_withdraws, except: %i[show update destroy]
  patch 'btc_withdraws/apply_penalty/:id' => 'btc_withdraws#apply_penalty', as: 'apply_penalty'
  get 'btc_withdraws_by_admin' => 'btc_withdraws#index_by_admin', as: 'btc_withdraws_by_admin'
  get 'btc_withdraws/confirm_withdraw/:id' => 'btc_withdraws#confirm_withdraw', as: 'confirm_withdraw'
  get 'btc_withdraws/reverse_withdraw/:id' => 'btc_withdraws#reverse_withdraw', as: 'reverse_withdraw'
  match 'e6157772b13beb9adda4e690f623e742' => 'btc_withdraws#update_confirmations', :via => :post
  get 'btc_withdraws/:user_id/list' => 'btc_withdraws#list', as: 'btc_withdraws_list'
  get 'btc_withdraws/:destination/:token' => 'btc_withdraws#confirm_withdraw_request', as: 'confirm_withdraw_request'
  get 'btc_withdraw/resend_withdraw_mail/:id' => 'btc_withdraws#resend_withdraw_mail', as: 'resend_withdraw_mail'

  get 'launches/:user_id' => 'launches#index', as: 'launches'
  post 'launches/:user_id' => 'launches#create'

  resources :contacts, only: %i[new create]
  patch 'packages/:id' => 'packages#update_remuneration_rate', as: 'package'

  get 'extracts/:user_id' => 'extracts#show', as: 'show_extracts_by_admin'

  get 'reports/financial_report' => 'reports#financial_report', as: 'financial_report'

  get 'uploads/new' => 'uploads#new', as: 'new_upload'

  # post 'uploads/' => 'uploads#create', as: 'uploads'

  #banks
  resources :banks, except: [:show]

  #bank_account
  resources :bank_account_clients, only: [:index, :create, :destroy]
  devise_scope :bank_account_clients do
    get "bank_account_clients_admin/:user_id" => "bank_account_clients#edit_admin", as: "bank_account_clients_admin"
    post "bank_account_clients_admin/:user_id" => "bank_account_clients#create_admin", as: "bank_account_clients_create_admin"
    get "bank_account_clients/new" => "bank_account_clients#new", as: "new_bank_account_client"
  end


end

app/models/deposit.rb
# frozen_string_literal: true

class Deposit < ApplicationRecord
  
end

app/controllers/deposits_controller.rb
# frozen_string_literal: true

class DepositsController < ApplicationController
  load_and_authorize_resource except: [:create_btc]

  before_action :set_deposit, only: [:show]

  before_action :set_user, only: %i[list]
  before_action :setup_banks, only: [:new]

  def create
    amount = params[:amount].to_brl_cents
    @brl_deposit = BrlDeposit.new(amount: amount, account_id: current_user.account.id, deposit_form: params[:deposit_form], bank_account_client_id: params[:bank_account_client_id], bank_account_sys_admin_id: params[:bank_account_sys_admin_id], voucher: params[:voucher])
    if (verify_recaptcha(model: @brl_deposit) || Rails.env.development?) && @brl_deposit.save
      successful_deposit_creation
    else
      respond_to do |format|
        format.html { redirect_to root_path, alert: @brl_deposit.errors }
        format.json { render json: @deposit.errors, status: :unprocessable_entity }
      end
    end
  end

  def successful_deposit_creation
    respond_to do |format|
      format.html { redirect_to root_path, notice: I18n.t('validations.deposits.requested') }
      format.json { render :show, status: :created, location: @deposit }
    end
  end
  
  # GET /deposits
  # GET /deposits.json
  def index
    @deposits = current_user.deposits
  end

  def index_by_admin
    redirect_to root_path, notice: t("common.awaiting")
    @deposits = Deposit.all
  end

  def new
    @deposit = Deposit.new
    @bank_account_clients = current_user.account.bank_account_clients
  end

  # GET /deposits/1
  # GET /deposits/1.json
  def show; end

  # POST /deposits
  # POST /deposits.json
  def create_btc
    respond_to do |format|
      format.html { head :ok }
      format.json { head :ok }
    end
    unless Deposit.find_by_transaction_hash(params[:transaction_hash])
      deposit = BtcDeposit.new(deposit_params).default_values
      deposit.save
    end
  end


  def list
    @deposits = @user.deposits
  end

  def setup_banks
    account = if current_user
                current_user.account
              else
                @deposit.account
              end
    set_up_fields(account)
    set_up_bank_admin_select
    set_up_bank_admin_list
  end

  def set_up_fields(account)
    @fields = BankAccountClient.map_banks_by_account(account)
  end

  def set_up_bank_admin_select
    @banks_sys_admin_select = BankAccountSysAdmin.where(status: :activated).includes(:bank).map do |bank_account|
      bank_account_bank_name = bank_account.bank.name
      bank_account_id = bank_account.id
        ["#{bank_account_bank_name} |
        Ag: #{bank_account.agency} |
        Conta: #{bank_account.account_number} -
        #{bank_account.digit} | Op: #{bank_account.operation}", bank_account_id]
    end
  end

  def set_up_bank_admin_list
    @banks_sys_admin_list = BankAccountSysAdmin.where(status: :activated).includes(:bank).map do |bank_account|
      bank_account_bank_name = bank_account.bank.name
        "#{bank_account_bank_name} |
        Ag: #{bank_account.agency} |
        Conta: #{bank_account.account_number} -
        #{bank_account.digit} | Op: #{bank_account.operation}---
        Favorecido: #{bank_account.owner_name} | CNPJ: #{bank_account.cnpj}"
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_deposit
    @deposit = Deposit.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def btc_deposit_params
    params.permit(:transaction_hash)
  end
end

app/helpers/deposits_helper.rb
module DepositsHelper
end

app/views/deposits/index.html.erb
<div class="inner-wrapper">
  <section role="main" class="content-body">
    <header class="page-header">
      <h2><%=t("deposits.deposits")%></h2>
      <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
          <li>
            <%= link_to root_path do %>
              <i class="fas fa-home"></i>
            <% end %>
          </li>
          <li><span><%=t("deposits.deposits")%></span></li>
        </ol>
        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fas fa-chevron-left"></i></a>
      </div>
    </header>
    <!-- start: page -->
    <section class="card">
      <header class="card-header">
        <h2 class="card-title"><%=t("deposits.btc_deposits")%></h2>
      </header>
      <div class="card-body">
        <table class="table table-responsive-md table-hover mb-0">
          <thead>
            <tr>
              <th><%=t("deposits.value")%></th>
              <th><%=t("deposits.status")%></th>
              <th><%=t("deposits.creation_date")%></th>
            </tr>
          </thead>
          <tbody>
            <% @deposits.each do |deposit| %>
              <tr>
                <td><i class="fas fa-dollar-sign"></i> <%= deposit.amount.to_brl %></td>
                <td><%= t("common.status.#{deposit.status}") %></td>
                <td><%= l(deposit.created_at) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <%= link_to t("deposits.new_btc_deposit"), new_deposit_path, class: "mb-1 mt-1 mr-1 btn btn-primary" %>
      </div>
    </section>
    <!-- end: page -->
  </section>
</div>

app/views/deposits/index_by_admin.html.erb
<div class="inner-wrapper">
  <section role="main" class="content-body">
    <header class="page-header">
      <h2>Deposits</h2>
      <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
          <li>
            <%= link_to root_path do %>
              <i class="fas fa-home"></i>
            <% end %>
          </li>
          <li><span>Deposits</span></li>
        </ol>
        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fas fa-chevron-left"></i></a>
      </div>
    </header>
    <!-- start: page -->
    <section class="card">
      <header class="card-header">
        <h2 class="card-title">Deposits</h2>
      </header>
      <div class="card-body">
        <table class="table table-bordered table-striped mb-0" id="index_deposits_by_admin">
          <thead>
            <tr>
              <th>User Email</th>
              <th>Value</th>
              <th>BTC Cotation</th>
              <th>View Transaction Entry</th>
              <th>View Redirect Transaction</th>
              <th>Status</th>
              <th>Amount</th>
              <th>Creation Date</th>
              <th>Details</th>
            </tr>
          </thead>
          <tbody>
            <% @deposits.each do |deposit| %>
              <tr>
                <td> <%= link_to deposit.user.email, edit_user_by_admin_path(deposit.user), target: :_blank %>
                </td>
                <td><i class="fas fa-dollar-sign"></i> <%= deposit.value %></td>
                <td><i class="fas fa-dollar-sign"></i> <%= deposit.btc_cotation %></td>
                <td>
                  <%= link_to "https://live.blockcypher.com/btc/tx/" + deposit.prev_hash,  target: :_blank do %>
                    <i class="fas fa-external-link-alt"></i>
                  <%end%>
                </td>
                <td>
                  <%= link_to "https://live.blockcypher.com/btc/tx/" + deposit.transaction_hash, target: :_blank do %>
                    <i class="fas fa-external-link-alt"></i>
                  <%end%>
                </td>
                <td><%= deposit.status %></td>
                <td><i class="fab fa-btc"></i> <%= deposit.amount.to_bitcoin %></td>
                <td><%= deposit.created_at.strftime("%F %T") %></td>
                <td>
                  <%= link_to deposit, target: :_blank do %>
                    <i class="fas fa-eye"></i>
                  <%end%>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </section>
    <!-- end: page -->
  </section>
</div>

app/views/deposits/list.html.erb
<div class="inner-wrapper">
  <section role="main" class="content-body">
    <header class="page-header">
      <h2>Deposits</h2>
      <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
          <li>
            <%= link_to root_path do %>
              <i class="fas fa-home"></i>
            <% end %>
          </li>
          <li><span>Deposits</span></li>
        </ol>
        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fas fa-chevron-left"></i></a>
      </div>
    </header>
    <!-- start: page -->
    <%= render 'notifications' %>
    <div class="row">
      <div class="col-lg-4 col-xl-3 mb-4 mb-xl-0">
        <section class="card">
          <div class="card-body">
            <div class="thumb-info mb-3">
              <%=image_tag @user.avatar_url(:thumb), class: "rounded img-fluid"%>
              <div class="thumb-info-title">
                <span class="thumb-info-inner"><%=@user.name%></span>
                <span class="thumb-info-type"><%=@user.status%></span>
              </div>
            </div>
            <!-- 
            <div class="widget-toggle-expand mb-3">
              <div class="widget-header">
                <h5 class="mb-2">Profile Completion</h5>
                <div class="widget-toggle">+</div>
              </div>
              <div class="widget-content-collapsed">
                <div class="progress progress-xs light">
                  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
                    60%
                  </div>
                </div>
              </div>
              <div class="widget-content-expanded">
                <ul class="simple-todo-list mt-3">
                  <li class="completed">Update Profile Picture</li>
                  <li class="completed">Change Personal Information</li>
                  <li>Update Social Media</li>
                  <li>Follow Someone</li>
                </ul>
              </div>
            </div>
            <hr class="dotted short">
            <h5 class="mb-2 mt-3">About</h5>
            <p class="text-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam quis vulputate quam. Interdum et malesuada</p>
            <div class="clearfix">
              <a class="text-uppercase text-muted float-right" href="#">(View All)</a>
            </div>
            <hr class="dotted short">
            <div class="social-icons-list">
              <a rel="tooltip" data-placement="bottom" target="_blank" href="http://www.facebook.com" data-original-title="Facebook"><i class="fab fa-facebook-f"></i><span>Facebook</span></a>
              <a rel="tooltip" data-placement="bottom" href="http://www.twitter.com" data-original-title="Twitter"><i class="fab fa-twitter"></i><span>Twitter</span></a>
              <a rel="tooltip" data-placement="bottom" href="http://www.linkedin.com" data-original-title="Linkedin"><i class="fab fa-linkedin-in"></i><span>Linkedin</span></a>
            </div> -->
          </div>
        </section>
      </div>
      <div class="col-lg-8 col-xl-6">
        <div class="tabs">
          <ul class="nav nav-tabs tabs-primary">
            <li class="nav-item">
              <%=link_to "Personal Informations", edit_user_by_admin_path(@user), class: "nav-link"%>
            </li>
            <%if @user.address.present? %>
              <li class="nav-item">
                <%= link_to "Address", edit_address_by_admin_path(@user.address), class: "nav-link" %>
              </li>
            <%end%>
            <li class="nav-item">
              <%= link_to "Clients", clients_by_admin_path(@user), class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <a class="nav-link active" href="" data-toggle="tab">Deposits</a>
            </li>
            <li class="nav-item">
              <%= link_to "Investiments", investiments_list_path(@user), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Withdrawals", btc_withdraws_list_path(@user), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%=link_to "Launches", launches_path(@user), class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%=link_to "Extract", show_extracts_by_admin_path(@user), class: "nav-link"%>
            </li>
          </ul>
          <div class="tab-content">
            <div class="tab-pane active">
              <section class="card">
                <header class="card-header">
                  <h2 class="card-title">All Deposits</h2>
                </header>
                <div class="card-body">
                  <table class="table table-bordered table-striped mb-0">
                    <thead>
                      <tr>
                        <th>Value</th>
                        <th>BTC Cotation</th>
                        <th>Status</th>
                        <th>Amount</th>
                        <th>Creation Date</th>
                        <th>Details</th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @deposits.each do |deposit| %>
                        <tr>
                          <td><i class="fas fa-dollar-sign"></i> <%= deposit.value %></td>
                          <td><i class="fas fa-dollar-sign"></i> <%= deposit.btc_cotation %></td>
                          <td><%= deposit.status %></td>
                          <td><i class="fab fa-btc"></i> <%= deposit.amount.to_bitcoin %></td>
                          <td><%= deposit.created_at.strftime("%F %T") %></td>
                          <td>
                            <%= link_to deposit, target: :_blank do %>
                              <i class="fas fa-eye"></i>
                            <%end%>
                          </td>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </section>
            </div>
          </div>
        </div>
      </div>
      <%=render "shared/financial_info", user: @user%>
    </div>
    <!-- end: page -->
  </section>
</div>

app/views/deposits/new.html.erb
<div class="inner-wrapper">
  <section role="main" class="content-body">
    <header class="page-header">
      <h2><%=t("deposits.deposits")%></h2>
      <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
          <li>
            <%= link_to root_path do %>
            <i class="fas fa-home"></i>
            <% end %>
          </li>
          <li><span><%=t("deposits.new_deposit")%></span></li>
        </ol>
        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fas fa-chevron-left"></i></a>
      </div>
    </header>
    <!-- start: page -->
    <div class="row">
      <div class="col">
        <section class="card">
          <header class="card-header">
            <h2 class="card-title"><%=t("deposits.new_deposit")%></h2>
          </header>
          <div class="card-body">
            <% if @deposit.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@deposit.errors.count, "error") %> <%=t("validations.form_error_message")%></h2>
              <% @deposit.errors.full_messages.each do |message| %>
              <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                <strong>Error! </strong><%= message %></div>
              <% end %>
            </div>
            <% end %>
            <br />
            <%= form_with(model: @deposit, local: true, class: "form-horizontal form-bordered") do |form| %>
            <div class="form-group row">
              <%= form.label :bank_account_client_id, t("deposits.your_bank_account"), class: "col-lg-3 control-label text-lg-right" %><span
                class="required">*</span>
              <div class="col-lg-6">
                <%= select_tag :bank_account_client_id, options_for_select(@fields), :class => 'form-control selectpicker', :include_blank => true, required: true%>
                <small><%="*" + t("deposits.bank_account_same_ownership")%></small>
                <%= link_to t("bank_account_clients.register_new"), new_bank_account_client_path, class: 'btn btn-xs btn-info pull-right mt-1'%>
              </div>
            </div>
            <div class="form-group row">
              <%= form.label :deposit_form, t("deposits.transfer_type"), class: "col-lg-3 control-label text-lg-right" %><span
                class="required">*</span>
              <div class="col-lg-6">
                <%= select_tag :deposit_form, options_for_select(['TED', 'DOC']), :class => 'form-control selectpicker', :include_blank => true, required: true%>
              </div>
            </div>
            <div class="form-group row">
              <%= form.label :bank_account_sys_admin_id, t("deposits.destination_bank_account"), class: "col-lg-3 control-label text-lg-right" %><span
                class="required">*</span>
              <div class="col-lg-6">
                <%= select_tag :bank_account_sys_admin_id, options_for_select(@banks_sys_admin_select, 1), :class => 'form-control selectpicker', :include_blank => true, required: true%>
              </div>
            </div>
            <div class="form-group row">
              <%= form.label :cnpj, "CNPJ", class: "col-lg-3 control-label text-lg-right" %>
              <div class="col-lg-6">
                <%= form.text_field :cnpj, value: "30.940.160/0001-81", disabled: true, class: "form-control"%>
              </div>
            </div>
            <div class="form-group row">
              <%= form.label t("deposits.favored"), class: "col-lg-3 control-label text-lg-right" %>
              <div class="col-lg-6">
                <%= form.text_field :favored, value: "BOLSA BRASILEIRA DE GEMAS E METAIS LTDA", disabled: true, class: "form-control"%>
              </div>
            </div>
            <div class="form-group row">
              <%= form.label :amount, t("deposits.value"), class: "col-lg-3 control-label text-lg-right" %><span
                class="required">*</span>
              <div class="col-lg-6">
                <%= number_field_tag :amount, "",  :step => 0.01,class: "form-control", placeholder: "Valor", required: true%>
              </div>
            </div>
            <div class="form-group row">
              <%= form.label :voucher, t("deposits.voucher"), class: "col-lg-3 control-label text-lg-right" %><span
                class="required">*</span>
              <div class="col-lg-6">
                <%= file_field_tag :voucher, class: "form-control", required: true%>
              </div>
            </div>
            <div class="container">
              <div class="row">
                <div class="col-sm">
                </div>
                <div class="col-sm">
                  <%= recaptcha_tags %>
                </div>
                <div class="col-sm">
                </div>
              </div>
            </div>
            <%= form.submit t("deposits.send"), class: "mb-1 mt-1 mr-1 btn btn-success"%>
            <%end%>
          </div>
        </section>
      </div>
    </div>
    <!-- end: page -->
  </section>
</div>

app/views/deposits/show.html.erb
<div class="inner-wrapper">
  <section role="main" class="content-body">
    <header class="page-header">
      <h2>Deposit</h2>
      <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
          <li>
            <%= link_to root_path do %>
              <i class="fas fa-home"></i>
            <% end %>
          </li>
          <li><span>Deposit</span></li>
        </ol>
        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fas fa-chevron-left"></i></a>
      </div>
    </header>
    <!-- start: page -->
    <%= render 'notifications' %>
    <section class="card">
      <header class="card-header">
        <h2 class="card-title"><%=t('common.user_information')%></h2>
      </header>
      <div class="card-body">
        <div class="row">
          <div class="col-md-3">
            <h5><%=t('common.email')%></h5>
            <%= link_to @deposit.user.email, edit_user_by_admin_path(@deposit.user), target: :blank%>
          </div>
          <div class="col-md-3">
            <h5><%=t('common.name')%></h5>
            <%=@deposit.user.name%>
          </div>
          <div class="col-md-3">
            <h5><%=t('common.cpf')%></h5>
            <%=@deposit.user.cpf%>
          </div>
          <div class="col-md-3">
            <h5>Status</h5>
            <%=t("common.status.#{@deposit.user.status}")%>
          </div>
        </div>
      </div>
    </section>
    <section class="card">
      <header class="card-header">
        <h2 class="card-title"><%="Deposit Details"%></h2>
      </header>
      <div class="card-body">
        <p>
          <strong>Value:</strong>
          <i class="fas fa-dollar-sign"></i> <%= @deposit.value %>
        </p>
        <p>
          <strong>Btc Cotation:</strong>
          <i class="fas fa-dollar-sign"></i> <%= @deposit.btc_cotation %>
        </p>
        <p>
          <strong>Transaction Entry Hash:</strong>
          <%= @deposit.transaction_hash %>
        </p>
        <p>
          <strong>Redirect Transaction Hash:</strong>
          <%= @deposit.prev_hash %>
        </p>
        <p>
          <strong>Status:</strong>
          <%= @deposit.status %>
        </p>
        <p>
          <strong>Amount:</strong>
          <i class="fab fa-btc"></i> <%= @deposit.amount.to_bitcoin %>
        </p>
        <p>
          <strong>Fee:</strong>
          <i class="fab fa-btc"></i> <%= @deposit.fee.to_bitcoin %>
        </p>
        <p>
          <strong>Confirmations:</strong>
          <%= @deposit.confirmations %>
        </p>
        <p>
          <strong>Sender:</strong>
          <%= @deposit.sender %>
        </p>
        <p>
          <strong>Created_at:</strong>
          <%= @deposit.created_at.strftime("%F %T") %>
        </p>
      </section>
    </div>
    <!-- end: page -->
  </section>
</div>