config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'dashboards#index'

  devise_for :users, skip: %i[registrations omniauth_callbacks unlocks], controllers: {
    confirmations: 'devise/users/confirmations',
    # omniauth_callbacks: 'devise/users/omniauth_callbacks',
    passwords: 'devise/users/passwords',
    # registrations: 'devise/users/registrations',
    sessions: 'devise/users/sessions'
  }

  devise_scope :user do
    get '/users/:referral_username/sign_up', to: 'devise/users/registrations#new', as: 'new_indication'
    get '/users/edit', to: 'devise/users/registrations#edit', as: 'edit_user_registration'
    patch '/users', to: 'devise/users/registrations#update', as: 'user_registration'
    put '/users', to: 'devise/users/registrations#update'
    post '/users', to: 'devise/users/registrations#create'
    get '/users/cancel', to: 'devise/users/registrations#cancel', as: 'cancel_user_registration'
    delete '/users', to: 'devise/users/registrations#destroy'
  end

  devise_for :admins, skip: %i[confirmations passwords registrations], controllers: {
    # confirmations: 'devise/admins/confirmations',
    # passwords: 'devise/admins/passwords',
    # registrations: 'devise/admins/registrations',
    sessions: 'devise/admins/sessions'
  }, path: '', path_names: { sign_in: 'nAw9D7t2hCLBJwDjPHnUhZJnSyESpf24cxjfsX6tvzCXHMVEahHf3qwyEg2r5DLy' }

  resources :addresses, except: %i[index show destroy]
  get 'addresses/:id/edit_by_admin' => 'addresses#edit_by_admin', as: 'edit_address_by_admin'

  get 'clients' => 'users#index_clients', as: 'index_clients'
  get 'clients_by_admin/:id' => 'users#index_clients_by_admin', as: 'clients_by_admin'
  get 'users' => 'users#index', as: 'index_users_by_admin'
  get 'users/:id/edit' => 'users#edit', as: 'edit_user_by_admin'
  patch 'users/:id' => 'users#update', as: 'user'

  resources :deposits, except: %i[edit update destroy] 
  match '548d82xh4gg5xt6cy8chvxnm6nmxvk6g' => 'deposits#create_btc', :via => :post
  get 'deposits_by_admin' => 'deposits#index_by_admin', as: 'deposits_by_admin'
  get 'deposits/:user_id/list' => 'deposits#list', as: 'deposits_list'

  resources :investiments, except: %i[destroy]
  get 'investiments_by_admin' => 'investiments#index_by_admin', as: 'investiments_by_admin'
  get 'investiments/activate/:id' => 'investiments#activate', as: 'activate_investiment'
  get 'investiments/disable/:id' => 'investiments#disable', as: 'disable_investiment'
  get 'investiments/:user_id/list' => 'investiments#list', as: 'investiments_list'
  post 'investiments/:user_id' => 'investiments#create_by_admin', as: 'create_investiment_by_admin'
  patch 'investiments/:id/edit_values' => 'investiments#edit_values', as: 'edit_investiment_values'

  resources :remunerations, except: %i[new create destroy show]
  get 'remunerations/pay/:id' => 'remunerations#pay', as: 'pay_remuneration'

  resources :btc_withdraws, except: %i[show update destroy]
  patch 'btc_withdraws/apply_penalty/:id' => 'btc_withdraws#apply_penalty', as: 'apply_penalty'
  get 'btc_withdraws_by_admin' => 'btc_withdraws#index_by_admin', as: 'btc_withdraws_by_admin'
  get 'btc_withdraws/confirm_withdraw/:id' => 'btc_withdraws#confirm_withdraw', as: 'confirm_withdraw'
  get 'btc_withdraws/reverse_withdraw/:id' => 'btc_withdraws#reverse_withdraw', as: 'reverse_withdraw'
  match 'e6157772b13beb9adda4e690f623e742' => 'btc_withdraws#update_confirmations', :via => :post
  get 'btc_withdraws/:user_id/list' => 'btc_withdraws#list', as: 'btc_withdraws_list'
  get 'btc_withdraws/:destination/:token' => 'btc_withdraws#confirm_withdraw_request', as: 'confirm_withdraw_request'
  get 'btc_withdraw/resend_withdraw_mail/:id' => 'btc_withdraws#resend_withdraw_mail', as: 'resend_withdraw_mail'

  get 'launches/:user_id' => 'launches#index', as: 'launches'
  post 'launches/:user_id' => 'launches#create'

  resources :contacts, only: %i[new create]
  patch 'packages/:id' => 'packages#update_remuneration_rate', as: 'package'

  get 'extracts/:user_id' => 'extracts#show', as: 'show_extracts_by_admin'

  get 'reports/financial_report' => 'reports#financial_report', as: 'financial_report'

  get 'uploads/new' => 'uploads#new', as: 'new_upload'

  # post 'uploads/' => 'uploads#create', as: 'uploads'

  #banks
  resources :banks, except: [:show]

  #bank_account
  resources :bank_account_clients, only: [:index, :create, :destroy]
  devise_scope :bank_account_clients do
    get "bank_account_clients_admin/:user_id" => "bank_account_clients#edit_admin", as: "bank_account_clients_admin"
    post "bank_account_clients_admin/:user_id" => "bank_account_clients#create_admin", as: "bank_account_clients_create_admin"
    get "bank_account_clients/new" => "bank_account_clients#new", as: "new_bank_account_client"
  end


end

app/models/investiment.rb
# frozen_string_literal: true

class Investiment < ApplicationRecord
  extend Enumerize

  has_paper_trail
  enumerize :status, in: %i[pending activated disabled canceled ], default: :pending
  belongs_to :user
  belongs_to :deposit, optional: true
  has_many :remunerations
  has_many :commissions

  def credit_accumulated(value)
    final_value = accumulated_value + value.abs
    update_attribute(:accumulated_value, final_value.round(2))
  end

  def create_with_balance
    if value >= 250
      if user.account.has_enough_available_funds?(value) && 
        user.account.debit_available(value)
        self.accumulated_value = self.value
        save
      else
        errors.add(:amount, I18n.t('validations.withdrawals.insufficient_funds'))
        false
      end
    else
      errors.add(:amount, I18n.t('validations.withdrawals.minimal_investiment'))
      false
    end 
  end


  def create_with_balance_by_admin
    if user.account.has_enough_available_funds?(value) && 
      user.account.debit_available(value)
      self.accumulated_value = self.value
      save
    else
      errors.add(:amount, I18n.t('validations.withdrawals.insufficient_funds'))
      false
    end
  end

  def activate
    if status.pending?
      set_expiration_date
      generate_remunerations
      update(status: :activated, activated_at: DateTime.now)     
      generate_direct_commissions
      generate_indirect_commissions
      NotifierActivatedInvestimentsMailer.notify_activated_investiment(self.user, self).deliver_now
    else
      false
    end
  end


  def disable
    if status.activated? && self.remunerations.where(status: :pending).empty?
      user.account.credit_available(accumulated_value)
      update(status: :disabled, disabled_at: DateTime.now)
      direct_indicator = User.find_by_id(user.user_id)
      direct_indicator&.update_consultor_level
    else
      false
    end
  end
  
  def edit_values(value, accumulated_value)
    if value.to_f != self.value || accumulated_value.to_f != self.accumulated_value
      self.update(value: value, accumulated_value: accumulated_value)
      remuneration_value = get_remuneration_value
      self.remunerations.update_all(value: remuneration_value)
    end
  end
  
  private

  def set_expiration_date
    update_attribute(:expiration_date, Date.today + 30.day)
  end

  def generate_remunerations
    initial_date = Date.today + 1.day
    expiration_date = self.expiration_date
    remuneration_value = get_remuneration_value
    iterator = 1

    (initial_date..expiration_date).each do |_date|
      Remuneration.create(number: iterator, value: remuneration_value, remuneration_date: _date, investiment: self)
      iterator += 1
    end
  end

  def generate_direct_commissions
    direct_indicator = User.find_by_id(user.user_id)
    direct_indicator&.update_consultor_level
    if direct_indicator.present?
      DirectCommission.create(user_id: direct_indicator.id, investiment_id: id)
    end
  end

  def generate_indirect_commissions
    direct_indicator = User.find_by_id(user.user_id)
    indirect_indicator = User.find_by_id(direct_indicator&.user_id)
    if direct_indicator.present? && indirect_indicator.present? && indirect_indicator.level.franchise?
      IndirectCommission.create(user_id: indirect_indicator.id, investiment_id: id)
    end
  end

  def get_remuneration_value
    (((remuneration_rate / 100) / 30.0) * value).round(2)
  end
end

app/controllers/investiments_controller.rb
# frozen_string_literal: true

class InvestimentsController < ApplicationController
  load_and_authorize_resource
  before_action :set_investiment, only: %i[show edit update activate disable edit_values]
  before_action :set_user, only: %i[list create_by_admin]

  def new
    if current_user.account.available_balance > 0
      @investiment = Investiment.new
      @remuneration_rate = Package.first.remuneration_rate
    else
      redirect_to new_deposit_path
    end
  end

  def create
    @investiment = Investiment.new(investiment_params)
    @investiment.user = current_user
    @investiment.remuneration_rate = Package.first.remuneration_rate
    respond_to do |format|
      if verify_recaptcha(model: @investiment) && @investiment.create_with_balance
        format.html { redirect_to investiment_path(@investiment), notice: 'Investiment was successfully created.' }
        format.json { render :show, status: :created, location: @investiment }
      else
        format.html { render :new }
        format.json { render json: @investiment.errors, status: :unprocessable_entity }
      end
    end
  end

  def create_by_admin
    @investiment = Investiment.new(create_by_admin_params)
    @investiment.user = @user
    @investiment.remuneration_rate = Package.first.remuneration_rate
    respond_to do |format|
      if @investiment.create_with_balance_by_admin
        format.html { redirect_to edit_investiment_path(@investiment), notice: 'Investiment was successfully created.' }
        format.json { render :edit, status: :created, location: @investiment }
      else
        format.html { render :list }
        format.json { render json: @investiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /investiments
  # GET /investiments.json
  def index
    @investiments = current_user.investiments
  end

  def index_by_admin
    all_investiments = Investiment.all
    if params[:status] == "pending"
      @investiments = all_investiments.where(status: :pending)
    elsif params[:status] == "activated"
      @investiments = all_investiments.where(status: :activated)
    elsif params[:status] == "disabled"
      @investiments = all_investiments.where(status: :disabled)
    elsif params[:status] == "canceled"
      @investiments = all_investiments.where(status: :canceled)
    elsif params[:status] == "all"
      @investiments = all_investiments
    end

  end

  # GET /investiments/1
  # GET /investiments/1.json
  def show
    @remunerations = @investiment.remunerations
   end

  # GET /investiments/1/edit
  def edit
    @remunerations = @investiment.remunerations
    @commissions = @investiment.commissions
  end

  # PATCH/PUT /investiments/1
  # PATCH/PUT /investiments/1.json
  def update
    respond_to do |format|
      if @investiment.update(update_investiment_params)
        format.html { redirect_to edit_investiment_path(@investiment), notice: 'Investiment was successfully updated.' }
        format.json { render :edit, status: :ok, location: @investiment }
      else
        format.html { render :edit }
        format.json { render json: @investiment.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit_values
    respond_to do |format|
      if @investiment.edit_values(edit_values_params[:value], edit_values_params[:accumulated_value])
        format.html { redirect_to edit_investiment_path(@investiment), notice: 'Investiment was successfully updated.' }
        format.json { render :edit, status: :ok, location: @investiment }
      else
        format.html { redirect_to edit_investiment_path(@investiment), alert: 'There was an error with your request, please try again' }
        format.json { render json: @investiment.errors, status: :unprocessable_entity }
      end
    end
  end

  def activate
    respond_to do |format|
      if @investiment.activate
        format.html { redirect_to edit_investiment_path(@investiment), notice: 'Investiment was successfully activated.' }
        format.json { render :edit, status: :ok, location: @investiment }
      else
        format.html { redirect_to edit_investiment_path(@investiment), alert: 'There was an error with your request, please try again' }
        format.json { render json: @investiment.errors, status: :unprocessable_entity }
      end
    end
  end

  def disable
    respond_to do |format|
      if @investiment.remunerations.where(status: :pending).size > 0
        format.html { redirect_to edit_investiment_path(@investiment), alert: "Só é possível desabilitar um investimento após o pagamento de todas as remunerações!" }
      else  
        if @investiment.disable
          format.html { redirect_to edit_investiment_path(@investiment), notice: 'Investiment was successfully disabled.' }
          format.json { render :edit, status: :ok, location: @investiment }
        else
          format.html { redirect_to edit_investiment_path(@investiment) }
          format.json { render json: @investiment.errors, status: :unprocessable_entity }
        end
      end 
    end
  end

  def list
    @investiments = @user.investiments
    @investiment = Investiment.new
  end

  private

  def set_user
    if user_signed_in?
      @user = current_user
    elsif admin_signed_in?
      @user = User.find(params[:user_id])
    end
   end

  # Use callbacks to share common setup or constraints between actions.
  def set_investiment
    @investiment = Investiment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def investiment_params
    params.require(:investiment).permit(:value)
  end
  
  def create_by_admin_params
    params.require(:investiment).permit(:value, :remuneration_rate)
  end

  def update_investiment_params
    params.require(:investiment).permit(:remuneration_rate)
  end

  def edit_values_params
    params.require(:investiment).permit(:value, :accumulated_value)
  end
end

app/helpers/investiments_helper.rb
module InvestimentsHelper
  def decide_tab_activate(type, type_params)
    if type == type_params
      "nav-link active"
    elsif type_params.nil? && type == "all"
      "nav-link active"
    else
      "nav-link"
    end
  end

  def get_size_filter_content_investiments(type_params)
    if type_params == "all"
      Investiment.count
    else
      Investiment.where(status: type_params).size
    end
  end
end

app/views/investiments/_commissions_by_admin.html.erb
<section class="card">
  <header class="card-header">
    <h2 class="card-title"><%=t("commissions.commissions")%></h2>
  </header>
  <div class="card-body">
    <table class="table table-bordered table-striped mb-0" id="index_commissions">
      <thead>
        <tr>
          <th>User</th>
          <th>Commission Rate</th>
          <th>Value</th>
          <th>Type</th>
          <th>Status</th>
          <th>Paid at</th>
        </tr>
      </thead>
      <tbody>
        <% @commissions.each do |commission| %>
          <tr>
            <td> <%= link_to commission.user.email, edit_user_by_admin_path(commission.user), target: :_blank %>
            </td>
            <td><%= commission.commission_rate * 100 %> %</td>
            <td><%= commission.value %></td>
            <td><%= commission.type %></td>
            <td><%= commission.status %></td>
            <td><%= commission.paid_at %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <!-- end: page -->
</section>

app/views/investiments/edit.html.erb
<div class="inner-wrapper">
  <section role="main" class="content-body">
    <header class="page-header">
      <h2><%=t("investiments.edit_investiment")%></h2>
      <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
          <li>
            <%= link_to root_path do %>
              <i class="fas fa-home"></i>
            <% end %>
          </li>
          <li><span><%=t("investiments.edit_investiment")%></span></li>
        </ol>
        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fas fa-chevron-left"></i></a>
      </div>
    </header>
    <!-- start: page -->
    <%= render 'notifications' %>
    <section class="card">
      <header class="card-header">
        <h2 class="card-title"><%=t('common.user_information')%></h2>
      </header>
      <div class="card-body">
        <div class="row">
          <div class="col-md-3">
            <h5><%=t('common.email')%></h5>
            <%= link_to @investiment.user.email, edit_user_by_admin_path(@investiment.user), target: :blank%>
          </div>
          <div class="col-md-3">
            <h5><%=t('common.name')%></h5>
            <%=@investiment.user.name%>
          </div>
          <div class="col-md-3">
            <h5><%=t('common.cpf')%></h5>
            <%=@investiment.user.cpf%>
          </div>
          <div class="col-md-3">
            <h5>Status</h5>
            <%=t("common.status.#{@investiment.user.status}")%>
          </div>
        </div>
      </div>
    </section>
    <br/>
    <div class="row">
      <div class="col">
        <section class="card">
          <header class="card-header">
            <h2 class="card-title"><%=t("investiments.edit_investiment")%></h2>
          </header>
          <div class="card-body">
            <%= form_with(model: @investiment, local: true) do |form| %>
              <% if @investiment.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@investiment.errors.count, "error") %> <%=t("validations.form_error_message")%></h2>
                  <% @investiment.errors.full_messages.each do |message| %>
                    <div class="alert alert-danger">
                      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                      <strong>Error! </strong><%= message %></div>
                  <% end %>
                </div>
              <% end %>
              <div class="form-group row">
                <%= form.label :value, class: "col-lg-3 control-label text-lg-right" %>
                <div class="col-lg-6">
                  <%= form.text_field :value, class: "form-control", disabled: "true"%>
                </div>
              </div>
              <div class="form-group row">
                <%= form.label :accumulated_value, class: "col-lg-3 control-label text-lg-right" %>
                <div class="col-lg-6">
                  <%= form.text_field :accumulated_value, class: "form-control", disabled: "true"%>
                </div>
              </div>
              <div class="form-group row">
                <%= form.label :expiration_date, class: "col-lg-3 control-label text-lg-right" %>
                <div class="col-lg-6">
                  <div class="input-group">
                    <span class="input-group-prepend">
                      <span class="input-group-text">
                        <i class="fas fa-calendar-alt"></i>
                      </span>
                    </span>
                    <%= form.date_field :expiration_date, class: "form-control", disabled: "true" %>
                  </div>
                </div>
              </div>
              <div class="form-group row">
                <%= form.label :created_at, class: "col-lg-3 control-label text-lg-right" %>
                <div class="col-lg-6">
                  <div class="input-group">
                    <span class="input-group-prepend">
                      <span class="input-group-text">
                        <i class="fas fa-calendar-alt"></i>
                      </span>
                    </span>
                    <%= form.date_field :created_at, class: "form-control", disabled: "true" %>
                  </div>
                </div>
              </div>
              <div class="form-group row">
                <%= form.label :remuneration_rate, class: "col-lg-3 control-label text-lg-right" %>
                <div class="col-lg-6">
                  <% if @investiment.status.activated?%>
                    <%= form.number_field :remuneration_rate, class: "form-control", disabled: "true" %>
                  <%else%>
                    <%= form.number_field :remuneration_rate, class: "form-control", step: ".01" %>
                  <%end%>
                </div>
              </div>
              <div class="form-group row">
                <%= form.label :status, class: "col-lg-3 control-label text-lg-right" %>
                <div class="col-lg-6">
                  <%= form.text_field :status, class: "form-control", disabled: "true" %>
                </div>
              </div>
              <% if @investiment.status.pending? %>
                <%= form.submit t("investiments.update"), class: "mb-1 mt-1 mr-1 btn btn-primary"%>
                <%= link_to "Activate", activate_investiment_path(@investiment), class: "mb-1 mt-1 mr-1 btn btn-success"%>
              <%elsif @investiment.status.activated?%>
                <%= link_to "Disable", disable_investiment_path(@investiment), class: "mb-1 mt-1 mr-1 btn btn-danger"%>
              <%end%>
            <% end %>
          </div>
        </section>
        <%= form_for @investiment, as: :investiment, url: edit_investiment_values_path(@investiment), method: :patch, html: {class: "form-horizontal form-bordered"} do |form| %>
          <section class="card">
            <header class="card-header">
              <h2 class="card-title">Edit Values</h2>
            </header>
            <div class="card-body">
              <div class="form-group row">
                <%= form.label :value, class: "col-lg-3 control-label text-lg-right" %>
                <div class="col-lg-6">
                  <%= form.text_field :value, class: "form-control", step: ".01", min: 0 %>
                </div>
              </div>
              <div class="form-group row">
                <%= form.label :accumulated_value, class: "col-lg-3 control-label text-lg-right" %>
                <div class="col-lg-6">
                  <%= form.text_field :accumulated_value, class: "form-control", step: ".01", min: 0 %>
                </div>
              </div>
              <%= form.submit t("investiments.update"), class: "mb-1 mt-1 mr-1 btn btn-primary"%>
            </div>
          </section>
        <% end %>
      </div>
    </div>
    <br>
    <%= render 'remunerations_by_admin' %>
    <%= render 'commissions_by_admin' %>
    <!-- end: page -->
  </section>
</div>

app/views/investiments/list.html.erb
<div class="inner-wrapper">
  <section role="main" class="content-body">
    <header class="page-header">
      <h2>Investiments</h2>
      <div class="right-wrapper text-right">
        <ol class="breadcrumbs">
          <li>
            <%= link_to root_path do %>
              <i class="fas fa-home"></i>
            <% end %>
          </li>
          <li><span>Investiments</span></li>
        </ol>
        <a class="sidebar-right-toggle" data-open="sidebar-right"><i class="fas fa-chevron-left"></i></a>
      </div>
    </header>
    <!-- start: page -->
    <%= render 'notifications' %>
    <div class="row">
      <div class="col-lg-4 col-xl-3 mb-4 mb-xl-0">
        <section class="card">
          <div class="card-body">
            <div class="thumb-info mb-3">
              <%=image_tag @user.avatar_url(:thumb), class: "rounded img-fluid"%>
              <div class="thumb-info-title">
                <span class="thumb-info-inner"><%=@user.name%></span>
                <span class="thumb-info-type"><%=@user.status%></span>
              </div>
            </div>
            <!-- 
            <div class="widget-toggle-expand mb-3">
              <div class="widget-header">
                <h5 class="mb-2">Profile Completion</h5>
                <div class="widget-toggle">+</div>
              </div>
              <div class="widget-content-collapsed">
                <div class="progress progress-xs light">
                  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
                    60%
                  </div>
                </div>
              </div>
              <div class="widget-content-expanded">
                <ul class="simple-todo-list mt-3">
                  <li class="completed">Update Profile Picture</li>
                  <li class="completed">Change Personal Information</li>
                  <li>Update Social Media</li>
                  <li>Follow Someone</li>
                </ul>
              </div>
            </div>
            <hr class="dotted short">
            <h5 class="mb-2 mt-3">About</h5>
            <p class="text-2">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam quis vulputate quam. Interdum et malesuada</p>
            <div class="clearfix">
              <a class="text-uppercase text-muted float-right" href="#">(View All)</a>
            </div>
            <hr class="dotted short">
            <div class="social-icons-list">
              <a rel="tooltip" data-placement="bottom" target="_blank" href="http://www.facebook.com" data-original-title="Facebook"><i class="fab fa-facebook-f"></i><span>Facebook</span></a>
              <a rel="tooltip" data-placement="bottom" href="http://www.twitter.com" data-original-title="Twitter"><i class="fab fa-twitter"></i><span>Twitter</span></a>
              <a rel="tooltip" data-placement="bottom" href="http://www.linkedin.com" data-original-title="Linkedin"><i class="fab fa-linkedin-in"></i><span>Linkedin</span></a>
            </div> -->
          </div>
        </section>
      </div>
      <div class="col-lg-8 col-xl-6">
        <div class="tabs">
          <ul class="nav nav-tabs tabs-primary">
            <li class="nav-item">
              <%=link_to "Personal Informations", edit_user_by_admin_path(@user), class: "nav-link"%>
            </li>
            <%if @user.address.present? %>
              <li class="nav-item">
                <%= link_to "Address", edit_address_by_admin_path(@user.address), class: "nav-link" %>
              </li>
            <%end%>
            <li class="nav-item">
              <%= link_to "Clients", clients_by_admin_path(@user), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Deposits", deposits_list_path(@user), class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <a class="nav-link active" href="" data-toggle="tab">Investiments</a>
            </li>
            <li class="nav-item">
              <%= link_to "Withdrawals", btc_withdraws_list_path(@user), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%=link_to "Launches", launches_path(@user), class: "nav-link"%>
            </li>
            <li class="nav-item">
              <%=link_to "Extract", show_extracts_by_admin_path(@user), class: "nav-link"%>
            </li>
          </ul>
          <div class="tab-content">
            <div class="tab-pane active">
              <section class="card">
                <header class="card-header">
                  <h2 class="card-title">All Investiments</h2>
                </header>
                <div class="card-body">
                  <table class="table table-bordered table-striped mb-0">
                    <thead>
                      <tr>
                        <th><%= t('investiments.value')%></th>
                        <th><%= t('investiments.expiration_date')%></th>
                        <th><%= t('investiments.remuneration_rate')%></th>
                        <th><%= t('investiments.status')%></th>
                        <th><%= t('investiments.details')%></th>
                      </tr>
                    </thead>
                    <tbody>
                      <% @investiments.each do |investiment| %>
                        <tr>
                          <td><i class="fas fa-dollar-sign"></i> <%= investiment.value %></td>
                          <td><%=investiment.expiration_date.blank? ? "" : l(investiment.expiration_date) %></td>
                          <td><%= investiment.remuneration_rate %> % A.M</td>
                          <td><%= t("common.status.#{investiment.status}") %></td>
                          <%if user_signed_in? %>
                            <td>
                              <%= link_to investiment, target: :_blank do %>
                                <i class="fas fa-eye"></i>
                              <%end%>
                            </td>
                          <%else%>
                            <td>
                              <%= link_to edit_investiment_path(investiment), target: :_blank do %>
                                <i class="fas fa-eye"></i>
                              <%end%>
                            </td>
                          <%end%>
                        </tr>
                      <% end %>
                    </tbody>
                  </table>
                </div>
              </section>
              <% if admin_signed_in? %>
                <section class="card">
                  <div class="card-header">
                    <h2 class="card-title"><%= t("investiments.new_investiment")%></h2>
                  </div>
                  <div class="card-body">
                    <% if @investiment.errors.any? %>
                      <div id="error_explanation">
                        <h2><%= pluralize(@investiment.errors.count, "error") %> <%=t("validations.form_error_message")%></h2>
                        <% @investiment.errors.full_messages.each do |message| %>
                          <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                            <strong>Error! </strong><%= message %></div>
                        <% end %>
                      </div>
                    <% end %>
                    <h3 class="text-center"><%=t("withdrawals.available_balance")%> <i class="fas fa-dollar-sign"></i>
                      <%= @user.account.available_balance%></h3>
                    <br />
                    <%= form_for @investiment, as: :investiment, url: create_investiment_by_admin_path(@user), method: :post, html: {class: "form-horizontal form-bordered"} do |form| %>
                      <div class="form-group row">
                        <%= form.label t("investiments.investiment_value"), class: "col-lg-3 control-label text-lg-right" %><span class="required">*</span>
                        <div class="col-lg-6">
                          <%= form.number_field :value, class: "form-control", step: ".01", placeholder: "USD value", required: true %>
                        </div>
                      </div>
                      <div class="form-group row">
                        <%= form.label t("investiments.remuneration_rate"), class: "col-lg-3 control-label text-lg-right" %>
                        <div class="col-lg-6">
                          <p>10 % A.M</p>
                        </div>
                      </div>
                      <%= form.submit t("investiments.submit_investiment"), class: "mb-1 mt-1 mr-1 btn btn-success"%>
                    <%end%>
                  </div>
                  <div class="card-footer">
                  </div>
                </section>
              <%end%>
            </div>
          </div>
        </div>
      </div>
      <%=render "shared/financial_info", user: @user%>
    </div>
    <!-- end: page -->
  </section>
</div>